version: "3"
services:
  repack:
    build:
      context: .
      target: alpine_repack
    image: "bdscan-repack:alpine"
    container_name: bdscan-repack
    volumes:
      - ".:/root/builder"
    working_dir: /root
    command: /bin/ash -c "
      ./builder/download.sh ${BDSCAN_ARCH:-} &&
      ./builder/build-deb.sh &&
      ./builder/build-apk.sh &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-deb:
    build:
      context: .
      target: "${BDSCAN_ARCH:-}debian_verify"
    image: "bdscan-verify-deb:${BDSCAN_ARCH:-}stretch"
    container_name: bdscan-verify-deb
    volumes:
      - ".:/mnt/builder"
    working_dir: /mnt/builder
    depends_on:
      - repack
    command: /bin/bash -c "
      while [ ! -f ./*-repack_*.deb ]; do sleep 1; done &&
      ./verify-deb.sh &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-apk:
    build:
      context: .
      target: "${BDSCAN_ARCH:-}alpine_verify"
    image: "bdscan-verify-apk:${BDSCAN_ARCH:-}alpine"
    container_name: bdscan-verify-apk
    volumes:
      - ".:/mnt/builder"
    working_dir: /mnt/builder
    depends_on:
      - repack
    command: /bin/ash -c "
      while [ ! -f ./*-repack.*.apk ]; do sleep 1; done &&
      ./verify-apk.sh &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL
