version: "3"
services:
  repack:
    build:
      context: .
      target: alpine_repack
    image: "bdscan-repack:alpine"
    container_name: bdscan-repack
    volumes:
      - ".:/root/builder"
    working_dir: /root
    command: /bin/ash -c "
      ./builder/download.sh ${BDSCAN_ARCH:-} &&
      ./builder/build-deb.sh ${BDSCAN_ARCH:-} &&
      ./builder/build-apk.sh ${BDSCAN_ARCH:-} &&
      ./builder/build-rpm.sh ${BDSCAN_ARCH:-} &&
      ./builder/download-cum.sh ${BDSCAN_ARCH:-} &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-deb:
    build:
      context: .
      target: "${BDSCAN_ARCH:-}debian_verify"
    image: "bdscan-verify-deb:${BDSCAN_ARCH:-}stretch"
    container_name: bdscan-verify-deb
    volumes:
      - ".:/mnt/builder"
    working_dir: /root
    depends_on:
      - repack
    command: /bin/bash -c "
      /mnt/builder/verify-deb.sh ${BDSCAN_ARCH:-} &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-apk:
    build:
      context: .
      target: "${BDSCAN_ARCH:-}alpine_verify"
    image: "bdscan-verify-apk:${BDSCAN_ARCH:-}alpine"
    container_name: bdscan-verify-apk
    volumes:
      - ".:/mnt/builder"
    working_dir: /root
    depends_on:
      - repack
    command: /bin/ash -c "
      /mnt/builder/verify-apk.sh ${BDSCAN_ARCH:-} &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-rpm:
    build:
      context: .
      target: "${BDSCAN_ARCH:-}centos_verify"
    image: "bdscan-verify-rpm:${BDSCAN_ARCH:-}centos"
    container_name: bdscan-verify-rpm
    volumes:
      - ".:/mnt/builder"
    working_dir: /root
    depends_on:
      - repack
    command: /bin/bash -c "
      /mnt/builder/verify-rpm.sh ${BDSCAN_ARCH:-} &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL
