version: "3"
services:
  repack:
    build: .
    image: "bdscan-repack:alpine"
    container_name: bdscan-repack
    volumes:
      - ".:/root/builder"
    working_dir: /root
    command: /bin/ash -c "
      ./builder/download.sh ${BDSCAN_ARCH:-} &&
      ./builder/build-deb.sh &&
      ./builder/build-apk.sh &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-deb:
    image: "debian:stretch-slim"
    container_name: bdscan-verify-deb
    volumes:
      - ".:/mnt/builder"
    working_dir: /mnt/builder
    environment:
      - LANG=C.UTF-8
    depends_on:
      - repack
    command: /bin/bash -c "
      ./verify-deb.sh &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL

  verify-apk:
    image: "alpine:3.11"
    container_name: bdscan-verify-apk
    volumes:
      - ".:/mnt/builder"
    working_dir: /mnt/builder
    environment:
      - LANG=C.UTF-8
    depends_on:
      - repack
    command: /bin/ash -c "
      ./verify-apk.sh &&
      tail -f /dev/null
      "
    stop_signal: SIGKILL
